### ISSUE TITLE
deepspeed multi-gpus training error

### ISSUE THREAD

**Issue by conglei2XU** [michael-wzhu/PromptCBLUE#10]
when initializing the pretrained using `model = hatGLMForConditionalGeneration.from_pretrained()` under the deepspeed.

**[partition_parameters.py:836_post_init_method]** prompt a warning "param weight in embedding not on GPU so was not" firstly.

Then "NotImplementError: Cannot copy out of meta tensor; no data!" raised from `self.word_embeddings = init_method()` on line 821 of **modeling_chatglm.py**

**Comment by michael-wzhu** [comment]
For distributed training, please refer to our [ChatMed repo](https://github.com/michael-wzhu/ChatMed)
