### ISSUE TITLE
is:issue is:closed 请问这个评测结果 和传统bert模型系列 得分可比吗？看这个结果 在分类和ner任务上 已经超越了传统bert模型了？

### ISSUE THREAD

**Issue by dotsonliu** [michael-wzhu/PromptCBLUE#12]
is:issue is:closed 请问这个评测结果 和传统bert模型系列 得分可比吗？看这个结果 在分类和ner任务上 已经超越了传统bert模型了？

**Comment by michael-wzhu** [comment]
似乎不能直接平行对比，但是应该来说LLM在多任务的instruction tuning肯定是非常有优势和可扩展性
