### ISSUE TITLE
请问作者构建的 PromptCBLUE 中子任务数据的比例分别是多少？

### ISSUE THREAD

**Issue by SupritYoung** [michael-wzhu/PromptCBLUE#3]
感谢主办方的数据！
我注意到 PromptCBLUE 中的数据来源于 CBLUE 中的不同任务数据。恳请主办方能否给出 PromptCBLUE 中各个类型数据的所占比例，以便我们保持继续保持类别均衡。

**Comment by michael-wzhu** [comment]
目前我们在天池提供的各个数据集中，每个子任务的样本量是大致相同的，参赛时候选手可以根据需要，自行调整训练集中每个子任务的样本比例。
测试集（A，B榜）中每个子任务的样本量也是大致相同的。
