### ISSUE TITLE
p-tuning的preprocess_function_eval函数代码好像没有改正

### ISSUE THREAD

**Issue by 5663015** [michael-wzhu/PromptCBLUE#4]
https://github.com/michael-wzhu/PromptCBLUE/blob/9fec7b10d9cf567b3a58bf9e2769b9de790fd5fb/src/ft_chatglm_ptuning/main.py#L202
之前fix了lora的`preprocess_function_eval`函数，但p-tuning的`preprocess_function_eval`在处理`test.json`时还是报错

**Comment by michael-wzhu** [comment]
p-tuning的preprocess_function_eval函数已更新
