### ISSUE TITLE
int8量化有问题

### ISSUE THREAD

**Issue by sjm1992st** [michael-wzhu/PromptCBLUE#5]
model = ChatGLMForConditionalGeneration.from_pretrained(
        model_args.model_name_or_path,
        config=config,
    ).half().cuda()
改成
    model = ChatGLMForConditionalGeneration.from_pretrained(
        model_args.model_name_or_path,
        config=config,
    ).quantize(8).half().cuda()
报错了

**Comment by michael-wzhu** [comment]
更改了模型加载方式，采用AutoModel.from_pretrained()加载，加载hf hub上最新的模型和代码
