### ISSUE TITLE
训练集中CMeEE部分数据问题

### ISSUE THREAD

**Issue by YaoChuanbiao** [michael-wzhu/PromptCBLUE#7]
在CMeEE的很多训练数据中，训练数据中已经规定好了有哪些实体类别，answer choice中蕴含的不是所有的实体类别，而是针对每条数据的类别子集，请问这样安排是为了什么呀，为什么不告诉大模型所有的实体类别，让大模型进行判断呢
在CMeIE中也是如此，只告诉了模型部分关系

**Comment by michael-wzhu** [comment]
如果指令要求抽取症状实体，target字段里面的实体就只有症状实体，不会有疾病实体。这是为了让模型根据指定的实体进行预测，考察其instruction following能力。同时，模型也需要有能力判断句子中是否有指定类型的实体，要能够在没有指定实体的情况下知道不做抽取才是对的

**Comment by YaoChuanbiao** [comment]
你好，我是姚传彪，您的邮件我已收到，我会认真阅读，在必要时给予回复。谢谢。
