### ISSUE TITLE
请问如何从指定的checkpoint继续训练

### ISSUE THREAD

**Issue by YaoChuanbiao** [michael-wzhu/PromptCBLUE#8]
请问从指定的checkpoint训练是，在命令行传入--resume_from_checkpoint $your_checkpopint_path/XX/XX等参数么
如果是的话，请问需要指定是哪一个模型呢？之前训练保存的checkpoint文件夹中有好几个模型文件，例如：adpter_model.bin、rng_state.pth、scheduler.pt等。

**Comment by michael-wzhu** [comment]
传入checkpoint文件夹的路径就行，剩下的交给huggingface判断了
